import type {
  ChatCapabilityAction,
  ChatActionType,
} from "./agent-action-contracts";

export const CHAT_CAPABILITY_ACTIONS: ChatCapabilityAction[] = [
  {
    type: "add_recommended_all",
    label: "추천 전체 담기",
    prompt: "추천 상품 전체를 장바구니에 담아줘",
    category: "cart",
    description: "추천된 상품을 한 번에 장바구니에 추가",
  },
  {
    type: "buy_recommended_all",
    label: "추천 전체 바로 구매",
    prompt: "추천 상품 전체를 바로 구매 진행해줘",
    category: "cart",
    description: "추천된 상품으로 즉시 주문 흐름 시작",
  },
  {
    type: "clear_cart",
    label: "장바구니 비우기",
    prompt: "장바구니를 비워줘",
    category: "cart",
    description: "장바구니 상품을 모두 제거",
  },
  {
    type: "open_cart",
    label: "장바구니 보기",
    prompt: "장바구니를 열어줘",
    category: "cart",
    description: "현재 담긴 상품을 확인",
  },
  {
    type: "start_chat_quick_check",
    label: "대화형 빠른검진",
    prompt: "빠른검진을 페이지 이동 없이 대화로 시작해줘",
    category: "assessment",
    description: "채팅 안에서 빠르게 문답 검진 진행",
  },
  {
    type: "start_chat_assess",
    label: "대화형 정밀검진",
    prompt: "정밀검진을 페이지 이동 없이 대화로 진행해줘",
    category: "assessment",
    description: "채팅 안에서 정밀 문항 검진 진행",
  },
  {
    type: "open_check_ai",
    label: "빠른검진으로 이동",
    prompt: "빠른검진 페이지로 이동해줘",
    category: "assessment",
    description: "빠른검진 전용 페이지로 이동",
  },
  {
    type: "open_assess",
    label: "정밀검진 페이지",
    prompt: "정밀검진 페이지로 이동해줘",
    category: "assessment",
    description: "정밀검진 전용 페이지로 이동",
  },
  {
    type: "open_profile",
    label: "프로필 설정",
    prompt: "프로필 설정을 열어줘",
    category: "account",
    description: "채팅 내 프로필 편집 모달 열기",
  },
  {
    type: "open_me",
    label: "내 정보 보기",
    prompt: "내 정보 페이지로 이동해줘",
    category: "account",
    description: "마이페이지로 이동",
  },
  {
    type: "open_my_orders",
    label: "내 주문 조회",
    prompt: "내 주문 조회 화면으로 이동해줘",
    category: "account",
    description: "주문 내역과 배송 상태를 확인하는 페이지로 이동",
  },
  {
    type: "open_my_data",
    label: "마이데이터 보기",
    prompt: "마이데이터 페이지를 열어줘",
    category: "account",
    description: "검진, 상담, 주문 데이터를 통합 조회",
  },
  {
    type: "open_auth_phone",
    label: "전화 인증 페이지",
    prompt: "전화번호 인증 페이지로 이동해줘",
    category: "account",
    description: "휴대폰 OTP 인증 화면으로 이동",
  },
  {
    type: "open_home",
    label: "홈으로 이동",
    prompt: "홈으로 이동해줘",
    category: "navigation",
    description: "메인 랜딩 페이지로 이동",
  },
  {
    type: "open_home_products",
    label: "상품 섹션으로 이동",
    prompt: "홈의 상품 섹션으로 이동해줘",
    category: "navigation",
    description: "홈의 상품 목록 영역으로 바로 이동",
  },
  {
    type: "focus_home_products",
    label: "상품 목록으로 이동",
    prompt: "현재 페이지에서 상품 섹션으로 바로 이동해줘",
    category: "page",
    description: "홈이나 탐색 페이지에서 이동 없이 상품 섹션으로 스크롤",
  },
  {
    type: "focus_linked_order_lookup",
    label: "연결 번호 주문조회",
    prompt: "현재 페이지에서 연결된 번호 주문 조회 영역으로 이동해줘",
    category: "page",
    description: "내 주문 페이지의 연결 번호 조회 영역으로 스크롤",
  },
  {
    type: "focus_manual_order_lookup",
    label: "수동 주문조회",
    prompt: "현재 페이지에서 수동 주문 조회 입력으로 이동해줘",
    category: "page",
    description: "내 주문 페이지의 수동 조회 입력 영역으로 스크롤",
  },
  {
    type: "focus_me_profile",
    label: "내 정보 프로필 영역",
    prompt: "현재 페이지에서 내 정보 프로필 설정 영역으로 이동해줘",
    category: "page",
    description: "/me 페이지의 프로필 편집 영역으로 스크롤",
  },
  {
    type: "focus_me_orders",
    label: "내 정보 주문 영역",
    prompt: "현재 페이지에서 내 주문 내역 영역으로 이동해줘",
    category: "page",
    description: "/me 페이지의 주문 내역 섹션으로 스크롤",
  },
  {
    type: "focus_my_data_account",
    label: "마이데이터 계정 정보",
    prompt: "현재 페이지에서 계정 정보 섹션으로 이동해줘",
    category: "page",
    description: "/my-data 페이지의 계정 요약 영역으로 스크롤",
  },
  {
    type: "focus_my_data_orders",
    label: "마이데이터 주문 내역",
    prompt: "현재 페이지에서 주문 내역 섹션으로 이동해줘",
    category: "page",
    description: "/my-data 페이지의 주문 내역 아코디언으로 스크롤",
  },
  {
    type: "focus_check_ai_form",
    label: "빠른검진 문항 영역",
    prompt: "현재 페이지에서 빠른검진 문항 영역으로 이동해줘",
    category: "page",
    description: "/check-ai 페이지의 질문과 제출 버튼 영역으로 스크롤",
  },
  {
    type: "focus_assess_flow",
    label: "정밀검진 진행 영역",
    prompt: "현재 페이지에서 정밀검진 진행 영역으로 이동해줘",
    category: "page",
    description: "/assess 페이지의 현재 검진 단계로 스크롤",
  },
  {
    type: "open_7day_purchase",
    label: "7일 패키지 보기",
    prompt: "7일 패키지 구매 섹션으로 이동해줘",
    category: "navigation",
    description: "7일 패키지 구매 시작 화면으로 이동",
  },
  {
    type: "open_explore",
    label: "상품 둘러보기",
    prompt: "상품 둘러보기 페이지로 이동해줘",
    category: "navigation",
    description: "탐색 페이지의 상품 섹션으로 이동",
  },
  {
    type: "open_chat_page",
    label: "AI 상담 전체 화면",
    prompt: "AI 상담 전체 화면으로 이동해줘",
    category: "navigation",
    description: "채팅 전체 화면으로 이동",
  },
  {
    type: "open_about",
    label: "회사 소개",
    prompt: "회사 소개 페이지를 열어줘",
    category: "support",
    description: "브랜드 소개 페이지로 이동",
  },
  {
    type: "open_contact",
    label: "문의하기",
    prompt: "문의하기 페이지를 열어줘",
    category: "support",
    description: "고객 문의 페이지로 이동",
  },
  {
    type: "open_terms",
    label: "이용약관",
    prompt: "이용약관 페이지를 열어줘",
    category: "support",
    description: "서비스 이용약관 페이지로 이동",
  },
  {
    type: "open_privacy",
    label: "개인정보처리방침",
    prompt: "개인정보처리방침 페이지를 열어줘",
    category: "support",
    description: "개인정보 처리방침 페이지로 이동",
  },
  {
    type: "open_refund_policy",
    label: "환불 규정",
    prompt: "환불 규정 페이지를 열어줘",
    category: "support",
    description: "취소와 환불 정책 페이지로 이동",
  },
  {
    type: "open_support_email",
    label: "문의 이메일",
    prompt: "문의 이메일 앱을 열어줘",
    category: "support",
    description: "기본 메일 앱에서 문의 메일 작성",
  },
  {
    type: "open_support_call",
    label: "고객센터 전화",
    prompt: "고객센터 전화 연결을 도와줘",
    category: "support",
    description: "전화 앱으로 문의 연결",
  },
  {
    type: "open_pharm_dashboard",
    label: "약국 주문 관리",
    prompt: "약국 주문 관리 페이지로 이동해줘",
    category: "operations",
    description: "약국 대시보드로 이동",
  },
  {
    type: "open_pharm_manage_products",
    label: "약국 상품 관리",
    prompt: "약국 상품 등록과 관리 페이지로 이동해줘",
    category: "operations",
    description: "약국 상품 등록과 수정 페이지로 이동",
  },
  {
    type: "open_rider_dashboard",
    label: "라이더 배송 관리",
    prompt: "라이더 배송 관리 페이지로 이동해줘",
    category: "operations",
    description: "라이더 대시보드로 이동",
  },
  {
    type: "open_admin_login",
    label: "관리자 로그인",
    prompt: "관리자 로그인 페이지로 이동해줘",
    category: "operations",
    description: "관리자 로그인 화면으로 이동",
  },
  {
    type: "open_admin_dashboard",
    label: "사이트 관리",
    prompt: "사이트 관리 페이지로 이동해줘",
    category: "operations",
    description: "관리자 대시보드로 이동",
  },
];

export const CHAT_ACTION_LABELS: Record<ChatActionType, string> =
  CHAT_CAPABILITY_ACTIONS.reduce(
    (acc, item) => {
      acc[item.type] = item.label;
      return acc;
    },
    {} as Record<ChatActionType, string>
  );
