export const HEALTH_LINK_COPY = {
  status: {
    linked: "Linked",
    authRequested: "Auth Requested",
    notLinked: "Not Linked",
  },
  flow: {
    fetch: {
      title: "Load checkup metrics",
      guide: "Start with summary data first to reduce paid API calls.",
    },
    sign: {
      title: "Complete Kakao auth",
      guide: "Finish auth in Kakao app, then press Next.",
    },
    init: {
      title: "Request Kakao auth",
      guide: "Enter name, birth date, and phone number, then press Next.",
    },
  },
  action: {
    next: "Next",
    reload: "Reload",
    unlink: "Unlink",
    refreshStatus: "Refresh status",
  },
  header: {
    title: "NHIS Checkup Link",
    description: "Default path is low-cost summary fetch. Detail mode only fetches limited recent data.",
    signInRequired: "Sign in with Kakao before linking.",
  },
  auth: {
    title: "Auth and Link",
    channelTitle: "Authenticate with Kakao",
    channelDescription: "Auth channel is fixed to Kakao in this deployment.",
    nameLabel: "Name",
    namePlaceholder: "Hong Gil-dong",
    birthLabel: "Birth date (YYYYMMDD)",
    birthPlaceholder: "19900101",
    phoneLabel: "Phone",
    phonePlaceholder: "01012345678",
    currentStepPrefix: "Current step",
    prerequisiteTitle: "Prerequisite required",
    prerequisiteDescription: "Enable the health checkup service in Health iN first, then retry.",
    prerequisiteLinkLabel: "Open Health iN",
    statusLoadFallback: "Failed to load link status.",
  },
  hook: {
    forceRefreshCooldownFallback:
      "Force refresh is temporarily blocked by cost guard. Please retry shortly.",
    targetPolicyBlockedPrefix:
      "Current cost policy allows checkup targets only. Blocked targets:",
    targetPolicyBlockedDefault:
      "Current cost policy allows checkup targets only.",
    budgetRetrySuffixPrefix: " Retry available in",
    budgetRetrySuffixUnit: "s.",
    budgetExceededDetailedPrefix:
      "Cost guard window reached. In the last",
    budgetExceededDetailedMiddle: "hours:",
    budgetExceededDetailedSuffix: "used.",
    budgetExceededFallback: "Cost guard window reached.",
    statusLoadFallback: "Failed to load link status.",
    inputNameRequired: "Please enter your name.",
    inputBirthInvalid: "Birth date must be in YYYYMMDD format.",
    inputPhoneInvalid: "Phone must contain 10-11 digits.",
    initFallback: "Failed to request authentication.",
    initNoticeReused:
      "Reused existing auth request state. Complete auth in Kakao, then continue.",
    initNoticeCreated:
      "Sent Kakao auth request. Complete auth in Kakao, then continue.",
    signFallback: "Failed to complete authentication.",
    signNoticeReused: "Authentication was already completed.",
    signNoticeCompleted: "Link authentication completed.",
    detailAlreadyLoadedNotice:
      "Detail metrics are already loaded. Reusing current result without additional paid calls.",
    unlinkFallback: "Failed to unlink.",
    unlinkNotice: "Unlinked successfully.",
  },
  workflow: {
    statusTitle: "Prepare link",
    statusSubtitle: "Enter identity and request auth",
    authTitle: "Complete Kakao auth",
    authSubtitle: "Approve and continue from Kakao",
    syncTitle: "Load checkup metrics",
    syncSubtitle: "Start with summary, then add detail if needed",
  },
  table: {
    rowUnit: "rows",
    previewHintPrefix: "Showing",
    previewHintMiddle: "of",
    previewHintSuffix: "rows.",
  },
  statusMeta: {
    detailSummary: "Link status details",
    lastErrorFallback: "Link error",
  },
  result: {
    title: "Checkup Metrics",
    description:
      "If summary data is insufficient, request detail metrics with the recent-1-year policy.",
    linkRequired: "Complete link auth first, then load data.",
    partialFailureTitle: "Partial fetch failures",
    empty: "No checkup metrics loaded yet.",
    metricRowsTitle: "Metric rows",
    metricRowsNote: "Filtered value-first metric rows",
    detailRowsTitle: "Detail rows (yearly)",
    detailRowsNote: "checkupYearly source rows",
    summaryRowsTitle: "Summary rows",
    summaryRowsNote: "checkupOverview source rows",
    limitedMetricInfo: "Summary data is shown because metric-style values were limited in this response.",
    tableTitle: "Core Checkup Metrics",
    tableEmpty: "No metric rows available for display.",
  },
  fetch: {
    cacheHitPrefix: "Cache hit (fetched",
    cacheHitInfix: ", expires",
    cacheHitSuffix: ")",
    liveResponse: "Live response",
    forceRefreshBlockedPrefix: "Force refresh is blocked for",
    forceRefreshBlockedMiddle: "s (until",
    forceRefreshBlockedSuffix: ").",
    forceRefreshBudgetBlockedPrefix: "Force refresh budget is exhausted for this window (",
    forceRefreshBudgetBlockedMiddle: "/",
    forceRefreshBudgetBlockedSuffix: ").",
    forceRefreshBudgetBlockedWindowPrefix: "Window",
    forceRefreshBudgetBlockedWindowSuffix: "h",
    forceRefreshDefault: "Force refresh triggers additional paid API calls.",
    confirmDetailSubject: "detail metrics",
    confirmSummarySubject: "summary data",
    confirmLine1Prefix: "This will force-refresh",
    confirmLine1Suffix: "without cache.",
    confirmLine2: "Additional API charges may occur. Continue?",
    detailButton: "Detail fetch (cost-capped: latest 1 year)",
    detailForceButton: "Force detail refresh (ignore cache)",
    summaryForceButton: "Force summary refresh (ignore cache)",
    detailHint: "Cost cap policy is applied.",
    detailAlreadyLoadedHint:
      "Detail metrics already loaded. Use force refresh only if you need to refresh now.",
  },
  raw: {
    summary: "Raw response (JSON)",
  },
} as const;
