export const NHIS_FORCE_REFRESH_COOLDOWN_ERR_CODE = "NHIS_FORCE_REFRESH_COOLDOWN";
export const NHIS_TARGET_POLICY_BLOCKED_ERR_CODE = "NHIS_TARGET_POLICY_BLOCKED";
export const NHIS_FETCH_DAILY_LIMIT_ERR_CODE = "NHIS_FETCH_DAILY_LIMIT";
export const NHIS_FORCE_REFRESH_DAILY_LIMIT_ERR_CODE = "NHIS_FORCE_REFRESH_DAILY_LIMIT";
