"use client";

const TEXT = {
  introBadge: "웰니스 리포트 사전 설문",
  introTitle: "웰니스박스 온라인 건강 설문",
  introDesc1: "현재 건강 상태와 생활 습관을 간편하게 확인해 보세요.",
  introDesc2: "예상 소요 시간은 약 5~7분이며, 입력한 내용은 자동으로 저장됩니다.",
  preAuthTitle: "설문 시작 전 카카오 본인인증",
  preAuthDesc: "임직원 리포트 데이터 통합을 위해 본인인증이 필요합니다.",
  namePlaceholder: "이름",
  birthPlaceholder: "생년월일 8자리",
  phonePlaceholder: "휴대폰 번호",
  sendAuth: "카카오톡으로 인증 보내기",
  resendAuth: "인증 다시 보내기",
  checkAuth: "카카오톡 인증 완료 후 확인",
  authDone: "인증 완료",
  authCheckingTitle: "인증 상태를 확인하는 중입니다",
  authCheckingDesc: "이전에 인증한 정보가 있는지 먼저 확인하고 있어요. 잠시만 기다려 주세요.",
  authLockedHint: "다른 정보로 진행하려면 아래 버튼을 눌러 입력 정보를 바꿔 주세요.",
  switchIdentity: "다른 정보로 설문 진행",
  startSurvey: "설문 시작하기",
  needAuthNotice: "본인인증을 완료하면 설문을 시작할 수 있어요.",
  completedRestartHint:
    "이미 완료한 설문 기록이 있어 다시 시작하면 답변이 초기화되고 처음부터 진행됩니다.",
  busyRequest: "인증 요청 중",
  busyChecking: "인증 확인 중",
  busyResending: "다시 보내는 중",
  busySyncing: "인증 정보 연결 중",
  errorInvalidIdentity: "이름, 생년월일 8자리, 휴대폰 번호를 정확히 입력해 주세요.",
  errorAuthRequestStalled: "인증 요청이 오래 걸리고 있어요. 다시 보내기를 눌러 주세요.",
  errorAuthConfirmStalled: "인증 확인이 오래 걸리고 있어요. 확인 버튼을 다시 눌러 주세요.",
  noticeAuthBySession: "이전에 확인된 인증 정보가 있어 바로 이어서 진행할 수 있어요.",
  noticeAuthByStoredIdentity: "저장된 인증 정보가 확인되어 바로 진행할 수 있어요.",
  noticeAuthRequested:
    "카카오톡으로 인증을 보냈어요. 카카오톡에서 인증을 마친 뒤 확인 버튼을 눌러 주세요.",
  noticeAuthComplete: "본인인증이 확인됐어요. 설문을 시작해 주세요.",
  noticeNeedResend: "인증 확인이 오래 걸리면 다시 보내기 후 확인 버튼을 눌러 주세요.",
  noticeSwitchedIdentity:
    "다른 정보로 다시 진행할 수 있도록 인증 상태를 초기화했어요.",
  renewalTitle: "현재 설문 개편 작업 중입니다",
  renewalDesc1: "일반 사용자는 아직 시작할 수 없어요.",
  renewalDesc2: "서비스 준비가 끝나면 별도 안내로 알려드릴게요.",
  close: "닫기",
  confirm: "확인",
  resetAsk: "처음부터 다시 시작할까요?",
  resetDesc: "지금까지 입력한 답변이 모두 초기화됩니다.",
  cancel: "취소",
  reset: "다시 시작",
  progressBarLabel: "진행률",
  sectionGuide: "현재 섹션 문항을 마치면 자동으로 다음 문항으로 넘어갑니다.",
  restart: "처음부터 다시 시작",
  commonSection: "공통 문항",
  commonBadge: "공통 설문",
  requiredBadge: "필수",
  optionalBadge: "선택",
  optionalHint: "해당 사항이 없으면 선택하지 않고 다음으로 넘어가도 됩니다.",
  sectionCounterPrefix: "섹션별 문항",
  prevQuestion: "이전 문항",
  prevSection: "이전 섹션",
  nextQuestion: "다음 문항",
  nextSection: "다음 섹션",
  sectionTransitionTitle: "선택한 분야 질문을 준비하고 있어요.",
  sectionTransitionDesc: "잠시만 기다려 주세요.",
  resultCheck: "결과 확인",
  submitSurvey: "설문 제출",
  editSurvey: "설문 답변 수정",
  resultTitle: "설문 결과",
  viewEmployeeReport: "내 건강 리포트 보기",
  scoreHealth: "건강 점수",
  scoreRisk: "생활 습관 위험도",
  scoreNeed: "건강관리 필요도 평균",
  submittedTitle: "설문을 제출했어요",
  submittedDesc:
    "제출한 내용은 안전하게 저장됐어요. 필요하면 답변을 수정하거나 처음부터 다시 시작할 수 있어요.",
} as const;

const CALCULATING_MESSAGES = [
  "입력한 내용을 정리하고 있어요.",
  "생활 습관 위험도를 계산하고 있어요.",
  "건강관리 필요도를 계산하고 있어요.",
  "결과를 준비하고 있어요.",
] as const;

export { TEXT, CALCULATING_MESSAGES };
