const TEXT = {
  introBadge: "웰니스 리포트 사전 설문",
  introTitle: "웰니스박스 온라인 건강 설문",
  introDesc1: "현재 건강 상태와 생활 습관을 간편하게 확인해 보세요.",
  introDesc2: "예상 소요 시간은 약 5~7분이며, 입력한 내용은 자동으로 저장됩니다.",
  preAuthTitle: "설문 시작 전 카카오 본인인증",
  preAuthDesc: "임직원 리포트 데이터 통합을 위해 본인인증이 필요합니다.",
  namePlaceholder: "이름",
  birthPlaceholder: "생년월일 8자리",
  phonePlaceholder: "휴대폰 번호",
  sendAuth: "카카오톡으로 인증 보내기",
  resendAuth: "카카오톡으로 인증 다시 보내기",
  checkAuth: "카카오톡 인증 완료 후 확인",
  authDone: "인증 완료",
  authCheckingTitle: "인증 상태를 확인하는 중입니다",
  authCheckingDesc: "이전 인증 정보를 조회하고 있어요. 잠시만 기다려 주세요.",
  authLockedHint: "다른 사람으로 진행하려면 아래 버튼을 눌러 정보를 변경해 주세요.",
  switchIdentity: "다른 사람으로 설문 진행",
  startSurvey: "설문 시작하기",
  needAuthNotice: "본인인증 완료 후 설문을 시작할 수 있습니다.",
  completedRestartHint:
    "완료된 설문 이력이 있어도 다시 시작하면 문항 선택값이 초기화되고 처음부터 진행됩니다.",
  busyRequest: "요청 중...",
  busyChecking: "확인 중...",
  errorInvalidIdentity: "이름, 생년월일(8자리), 휴대폰 번호를 정확히 입력해 주세요.",
  noticeAuthBySession: "이전 인증 세션을 확인했습니다. 설문을 이어서 진행해 주세요.",
  noticeAuthByStoredIdentity: "이전에 인증한 정보가 확인되어 바로 진행할 수 있습니다.",
  noticeAuthRequested:
    "카카오톡으로 인증을 보냈습니다. 카카오톡에서 인증 완료 후 확인을 눌러 주세요.",
  noticeAuthComplete: "본인인증 및 데이터 연동이 완료되었습니다. 설문을 시작해 주세요.",
  noticeNeedResend: "인증 요청이 만료되었습니다. 카카오톡으로 인증을 다시 보내주세요.",
  noticeSwitchedIdentity: "다른 사람 정보로 진행할 수 있도록 인증 세션을 초기화했습니다.",
  renewalTitle: "현재 설문 리뉴얼 중입니다",
  renewalDesc1: "일반 사용자는 아직 시작할 수 없습니다.",
  renewalDesc2: "서비스 점검 중이며 이용 가능 시점은 별도 공지로 안내드리겠습니다.",
  close: "닫기",
  confirm: "확인",
  resetAsk: "처음부터 다시 시작할까요?",
  resetDesc: "지금까지 입력한 설문 답변이 모두 초기화됩니다.",
  cancel: "취소",
  reset: "다시 시작",
  progressBarLabel: "진행률",
  sectionGuide: "현재 섹션 문항에 답하면 자동으로 다음 문항으로 이동합니다.",
  restart: "처음부터 다시 시작",
  commonSection: "공통 문항",
  commonBadge: "공통 설문",
  requiredBadge: "필수",
  optionalBadge: "선택",
  optionalHint: "해당 사항이 없으면 선택하지 않고 다음으로 넘어가도 됩니다.",
  sectionCounterPrefix: "섹션 내 문항",
  prevQuestion: "이전 문항",
  prevSection: "이전 섹션",
  nextQuestion: "다음 문항",
  nextSection: "다음 섹션",
  sectionTransitionTitle: "선택한 분야 문항을 불러오는 중입니다.",
  sectionTransitionDesc: "잠시만 기다려 주세요.",
  resultCheck: "결과 확인",
  submitSurvey: "설문 제출",
  editSurvey: "설문 답안 수정",
  resultTitle: "설문 결과",
  viewEmployeeReport: "내 건강 레포트 보기",
  scoreHealth: "건강점수",
  scoreRisk: "생활습관 위험도",
  scoreNeed: "건강관리 필요도 평균",
  submittedTitle: "설문이 제출되었습니다.",
  submittedDesc: "제출하신 내용은 정상 저장되었습니다. 필요하면 답안을 수정하거나 처음부터 다시 시작할 수 있습니다.",
} as const;

const CALCULATING_MESSAGES = [
  "입력 정보를 정리하고 있습니다.",
  "생활습관 위험도를 계산하고 있습니다.",
  "건강관리 필요도를 계산하고 있습니다.",
  "결과를 준비하고 있습니다.",
] as const;

export { TEXT, CALCULATING_MESSAGES };
