export type {
  DockPanelSize,
  DockResizeEdge,
  DockResizeState,
  DockPanelPosition,
  DockDragState,
  DocumentScrollLockSnapshot,
} from "./DesktopChatDock.layout.geometry";
export {
  clampDockSize,
  getDefaultDockSize,
  clampDockPosition,
  getDefaultDockPosition,
  findScrollableWithinBoundary,
  shouldPreventScrollChain,
  blurFocusedDescendant,
  edgeIncludesLeft,
  edgeIncludesRight,
  edgeIncludesTop,
  edgeIncludesBottom,
  resizeCursorForEdge,
} from "./DesktopChatDock.layout.geometry";

export type { FooterCartBarLayoutDetail } from "./DesktopChatDock.layout.storage";
export {
  DOCK_RESIZE_HINT_DISMISS_KEY,
  DOCK_RESIZE_HINT_WIDTH,
  FOOTER_CART_BAR_LAYOUT_EVENT,
  MOBILE_TRIGGER_BREAKPOINT,
  MOBILE_TRIGGER_EXTRA_GAP,
  DOCK_NUDGE_AUTO_HIDE_COOLDOWN_MS,
  DOCK_NUDGE_MANUAL_HIDE_COOLDOWN_MS,
  emitChatDockLayout,
  isFooterCartBarLayoutDetail,
  readFooterCartBarOffsetPx,
  queueDockPrompt,
  consumeDockPrompt,
  isDockNudgeDismissed,
  dismissDockNudge,
  isDockNudgeGloballySuppressed,
  suppressDockNudgeGlobally,
  loadDockSize,
  saveDockSize,
  loadDockPosition,
  saveDockPosition,
} from "./DesktopChatDock.layout.storage";
