export const ORDER_STATUS = {
  PAYMENT_COMPLETE: "결제 완료",
  COUNSEL_COMPLETE: "상담 완료",
  DISPENSE_COMPLETE: "조제 완료",
  PICKUP_COMPLETE: "픽업 완료",
  DELIVERY_COMPLETE: "배송 완료",
  CANCELED: "주문 취소",
} as const;

export type OrderStatus = typeof ORDER_STATUS[keyof typeof ORDER_STATUS];

export const ORDER_STATUS_STEPS: OrderStatus[] = [
  ORDER_STATUS.PAYMENT_COMPLETE,
  ORDER_STATUS.COUNSEL_COMPLETE,
  ORDER_STATUS.DISPENSE_COMPLETE,
  ORDER_STATUS.PICKUP_COMPLETE,
  ORDER_STATUS.DELIVERY_COMPLETE,
];
